spring:
  application:
    name: fabrick-banking-service
  datasource:
    url: jdbc:h2:mem:fabrickdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

fabrick:
  api:
    base-url: https://sandbox.platfr.io
    auth-schema: S2S
    api-key: ${FABRICK_API_KEY:FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP}
    account-id: ${FABRICK_ACCOUNT_ID:14537780}
    time-zone: Europe/Rome

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.example.fabrick: INFO
    org.springframework.web: INFO